# Generated by Django 4.1.7 on 2023-08-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(max_length=250, verbose_name='Digite Apellidos'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='direccionVenta',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Dirección de punto de venta'),
        ),
    ]
