# Generated by Django 4.1.7 on 2023-08-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Personas', '0002_alter_cliente_apellido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='direccionEmpresa',
            field=models.CharField(max_length=250, verbose_name='Dirección de contacto'),
        ),
    ]
